In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import statsmodels.api as sm
from tqdm import tqdm
from nba import NBAbase, NBAetl, NBAdata, NBAmodels
from betting import funcs
odds = funcs.odds()
import pickle
import shap
from nba_api.stats.endpoints import LeagueDashPtStats

In [89]:
etl = NBAetl.etl()
data = NBAdata.data()
threes = NBAmodels.models('threes')

In [94]:
df = pd.read_sql("select * from pgames where game_date = '2025-10-21'",etl.conn)

In [98]:
td = data.clean_na(threes.data)

In [101]:
qdf = pd.read_sql('''


-- This primiarily calculates rolling fields and game information for the days game to be used in the model.
-- Need to check game info in the future to see if we can preload a schedule
-- Shot attempts will be done in seperate queries as they are going through a python function for the rolling information
-- Future updates - how to incorporate inactives, can do a rolling value but would like more information on who is out and impact

SELECT 
--y
threesMade,

--identifiers
name, player_id, game_id, game_date, season, team,

--demo data
height, exp,

--shot locations, will have percentiles done in pandas
ra_fga, paint_fga, mid_fga, (COALESCE(lc_fga,0) + COALESCE(rc_fga,0)) crn_fga, abv_fga,
--minFirst, crnFgaFirst, abvFgaFirst,

--games info
CASE WHEN daysBetweenGames > 9 THEN 10 ELSE daysBetweenGames END AS daysBetweenGames,
gamesInFive, gamesInThree, oppGamesFive, OppGamesThree,
CASE WHEN oppDaysLastGame > 9 THEN 10 ELSE oppDaysLastGame END AS oppDaysLastGame,
CASE WHEN daysBetweenGames > 9  THEN 10 ELSE daysBetweenGames END -
CASE WHEN oppDaysLastGame > 9 THEN 10 ELSE oppDaysLastGame END AS netRest,

 home, tmGameCt, starter,
--rolling offensive (5 games and season) metrics
AVG(starter) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 11 PRECEDING AND 1 PRECEDING) AS mvAvgstart, 
AVG(threesMade) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS mvAvgThrees,
AVG(usagePercentage) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS mvAvgUsage,
AVG(offensiveRating) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) AS mvAvgOffRating,
AVG(marginOffRating) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) as mvAvgMarginOffRating,
AVG(min) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) as mvAvgMinutes,

    
SUM(ftm) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) * 1.0
/ SUM(fta) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) as mvAvgFtPrct,

SUM(lc_fgm+rc_fgm + abv_fgm) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) * 1.0
/    SUM(lc_fga + rc_fga + abv_fga) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN 6 PRECEDING AND 1 PRECEDING) as mvAvgThrPtPrct,    

AVG(usagePercentage) OVER (PARTITION BY season,player_id
    ORDER BY game_date ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS seasonUsage,
AVG(offensiveRating) OVER (PARTITION BY season,player_id
    ORDER BY game_date ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS seasonOffRating,
    
SUM(ftm) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) * 1.0
/ SUM(fta) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as seasonFtPrct,
SUM(lc_fgm+rc_fgm + abv_fgm) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) * 1.0
/    SUM(lc_fga + rc_fga + abv_fga) OVER (PARTITION BY season,player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as seasonThrPtPrct,

--career metrics
SUM(ftm) OVER (PARTITION BY player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) * 1.0
/ SUM(fta) OVER (PARTITION BY player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING)  as careerFtPrct,
    
SUM(lc_fgm+rc_fgm + abv_fgm) OVER (PARTITION BY player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) * 1.0
/    SUM(lc_fga + rc_fga + abv_fga) OVER (PARTITION BY player_id
    ORDER BY plyrGameCt ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) as careerThrPtPrct, 

AVG(usagePercentage) OVER (PARTITION BY player_id
    ORDER BY game_date ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS careerUsage,
AVG(offensiveRating) OVER (PARTITION BY player_id
    ORDER BY game_date ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS careerOffRating,
AVG(threesMade) OVER (PARTITION BY player_id
    ORDER BY game_date ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) AS careerAvgThrees,
    

-- defensive information
opp_id, 
--moving (5 games) and season averages
mvAvgOppPace, mvAvgOppOpen3, mvAvgOppWide3, mvAvgOppDefrating, 
seasonOppPace,  seasonOppOpen3,  seasonOppWide3,  seasonOppDefRating


FROM pgames
WHERE player_id in 
                    (SELECT player_id
                    FROM pgames 

                    group by player_id,season

                    HAVING (AVG(min) > 15
                    and max(plyrGameCt) >= 16)

    )

order by game_date

''',etl.conn)

In [106]:
predData = data.threes_pipe(qdf[qdf.game_date=='2025-10-21'])

/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)
/opt/anaconda3/lib/python3.11/site-packages/pandas/core/window/rolling.py:609: RuntimeWarning: All-NaN slice encountered
  return func(x, start, end, min_periods, *numba_args)

In [109]:
final = data.clean_na(predData)

In [110]:
final

,threesMade,name,player_id,game_id,game_date,season,team,height,exp,daysBetweenGames,...,crn_kurtSkew,crn_fgaMv,abv_fgaMv,threesMadeMv,cornerRatio,crn_interaction,abv_interaction,wide_interaction,crResid_interaction,usage_interaction
0,0,Kevon Looney,1626172,0022500002,2025-10-21,0,GSW,81.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0,Christian Wood,1626174,0022500002,2025-10-21,0,LAL,80.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0,Buddy Hield,1627741,0022500002,2025-10-21,0,GSW,76.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0,Gary Payton II,1627780,0022500002,2025-10-21,0,GSW,74.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0,Fred VanVleet,1627832,0022500001,2025-10-21,0,HOU,72.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0,Alex Caruso,1627936,0022500001,2025-10-21,0,OKC,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0,Isaiah Hartenstein,1628392,0022500001,2025-10-21,0,OKC,84.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0,Dillon Brooks,1628415,0022500001,2025-10-21,0,HOU,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0,Shai Gilgeous-Alexander,1628983,0022500001,2025-10-21,0,OKC,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0,Aaron Holiday,1628988,0022500001,2025-10-21,0,HOU,72.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0,De'Anthony Melton,1629001,0022500002,2025-10-21,0,GSW,75.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0,Jarred Vanderbilt,1629020,0022500002,2025-10-21,0,LAL,80.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,0,Kenrich Williams,1629026,0022500001,2025-10-21,0,OKC,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,0,Rui Hachimura,1629060,0022500002,2025-10-21,0,LAL,80.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0,Gabe Vincent,1629216,0022500002,2025-10-21,0,LAL,74.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,0,Cam Reddish,1629629,0022500002,2025-10-21,0,LAL,79.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,0,Jaxson Hayes,1629637,0022500002,2025-10-21,0,LAL,84.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,0,Luguentz Dort,1629652,0022500001,2025-10-21,0,OKC,76.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,0,Isaiah Joe,1630198,0022500001,2025-10-21,0,OKC,75.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,0,Jalen Green,1630224,0022500001,2025-10-21,0,HOU,76.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,0,Jonathan Kuminga,1630228,0022500002,2025-10-21,0,GSW,79.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,0,Jae'Sean Tate,1630256,0022500001,2025-10-21,0,HOU,76.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,0,Lindy Waters III,1630322,0022500002,2025-10-21,0,GSW,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,0,Moses Moody,1630541,0022500002,2025-10-21,0,GSW,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,0,Austin Reaves,1630559,0022500002,2025-10-21,0,LAL,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,0,Alperen Sengun,1630578,0022500001,2025-10-21,0,HOU,83.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,0,Aaron Wiggins,1630598,0022500001,2025-10-21,0,OKC,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,0,Jabari Smith Jr.,1631095,0022500001,2025-10-21,0,HOU,83.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,0,Chet Holmgren,1631096,0022500001,2025-10-21,0,OKC,85.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,0,Tari Eason,1631106,0022500001,2025-10-21,0,HOU,80.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,0,Max Christie,1631108,0022500002,2025-10-21,0,LAL,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,0,Jalen Williams,1631114,0022500001,2025-10-21,0,OKC,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,0,Jaylin Williams,1631119,0022500001,2025-10-21,0,OKC,81.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,0,Trayce Jackson-Davis,1631218,0022500002,2025-10-21,0,GSW,81.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,0,Amen Thompson,1641708,0022500001,2025-10-21,0,HOU,79.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,0,Cam Whitmore,1641715,0022500001,2025-10-21,0,HOU,79.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,0,Cason Wallace,1641717,0022500001,2025-10-21,0,OKC,75.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,0,Brandin Podziemski,1641764,0022500002,2025-10-21,0,GSW,76.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,0,Dalton Knecht,1642261,0022500002,2025-10-21,0,LAL,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,0,Ajay Mitchell,1642349,0022500001,2025-10-21,0,OKC,77.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,0,Quinten Post,1642366,0022500002,2025-10-21,0,GSW,84.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,0,Jeff Green,201145,0022500001,2025-10-21,0,HOU,80.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,0,Stephen Curry,201939,0022500002,2025-10-21,0,GSW,74.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,0,Anthony Davis,203076,0022500002,2025-10-21,0,LAL,82.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,0,Draymond Green,203110,0022500002,2025-10-21,0,GSW,78.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,0,Dennis Schroder,203471,0022500002,2025-10-21,0,GSW,73.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,0,Steven Adams,203500,0022500001,2025-10-21,0,HOU,83.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,0,Kyle Anderson,203937,0022500002,2025-10-21,0,GSW,81.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,0,Andrew Wiggins,203952,0022500002,2025-10-21,0,GSW,79.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,0,LeBron James,2544,0022500002,2025-10-21,0,LAL,81.0,0.0,10.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [116]:
threes.model.params.index[1:]

Index(['cornerRatio', 'abv_interaction', 'crn_interaction', 'netRest',
       'mvAvgThrees', 'mvAvgOppWide3', 'crn_fgaMv', 'abv_fgaMv',
       'threes_residualsAllowedMv', 'careerThrPtPrct'],
      dtype='object')

In [117]:
threes.model.predict(sm.add_constant(final.filter(threes.model.params.index[1:])))

,0,1,2,3,4,5,6,7,8,9,10
0,0.277980,0.321992,0.214410,0.106633,0.051219,0.016801,0.007049,0.002937,0.000744,0.000200,0.000036
1,0.237960,0.303130,0.241227,0.125196,0.060788,0.019050,0.008378,0.003121,0.000815,0.000288,0.000047
2,0.160569,0.278682,0.278528,0.155000,0.083747,0.024837,0.011884,0.004852,0.001138,0.000635,0.000130
3,0.278829,0.311982,0.220095,0.110395,0.051513,0.016631,0.007025,0.002601,0.000700,0.000198,0.000031
4,0.179317,0.284337,0.270860,0.148231,0.077335,0.023193,0.010867,0.004217,0.001031,0.000515,0.000096
5,0.260353,0.304480,0.232012,0.118569,0.055672,0.017623,0.007600,0.002692,0.000732,0.000233,0.000035
6,0.337191,0.305277,0.198605,0.096376,0.041164,0.013529,0.005474,0.001727,0.000523,0.000118,0.000014
7,0.213922,0.296266,0.253607,0.134426,0.067026,0.020632,0.009303,0.003501,0.000894,0.000362,0.000062
8,0.242791,0.302286,0.239984,0.124262,0.059683,0.018708,0.008199,0.002978,0.000790,0.000274,0.000044
9,0.262038,0.304741,0.231196,0.117997,0.055299,0.017523,0.007546,0.002669,0.000727,0.000230,0.000035
10,0.227011,0.299726,0.247145,0.129540,0.063562,0.019744,0.008784,0.003269,0.000847,0.000319,0.000053
11,0.331515,0.305248,0.201231,0.098038,0.042112,0.013796,0.005608,0.001777,0.000535,0.000124,0.000015
12,0.261736,0.307709,0.229520,0.116855,0.055250,0.017590,0.007560,0.002771,0.000741,0.000231,0.000036
13,0.257888,0.304085,0.233207,0.119409,0.056221,0.017769,0.007681,0.002726,0.000740,0.000238,0.000036
14,0.230972,0.299028,0.246197,0.128799,0.062606,0.019449,0.008628,0.003139,0.000825,0.000306,0.000049
15,0.264785,0.305152,0.229868,0.117069,0.054697,0.017363,0.007457,0.002632,0.000719,0.000224,0.000033
16,0.337180,0.305277,0.198611,0.096380,0.041166,0.013529,0.005474,0.001728,0.000523,0.000118,0.000014
17,0.209549,0.292435,0.257337,0.137228,0.068298,0.020872,0.009472,0.003472,0.000895,0.000376,0.000063
18,0.205183,0.292916,0.258394,0.138112,0.069481,0.021228,0.009667,0.003634,0.000922,0.000394,0.000068
19,0.184050,0.284255,0.269712,0.147172,0.075848,0.022761,0.010620,0.004008,0.000998,0.000488,0.000088
20,0.290921,0.303255,0.220320,0.110509,0.049490,0.015834,0.006666,0.002175,0.000629,0.000177,0.000023
21,0.275007,0.311537,0.221922,0.111635,0.052309,0.016848,0.007142,0.002652,0.000711,0.000205,0.000032
22,0.204054,0.306620,0.250341,0.132343,0.069377,0.021656,0.009777,0.004332,0.001009,0.000405,0.000085
23,0.244034,0.304607,0.238120,0.122950,0.059314,0.018669,0.008160,0.003033,0.000796,0.000272,0.000044
24,0.221586,0.296058,0.251219,0.132544,0.065039,0.020054,0.008986,0.003270,0.000854,0.000335,0.000055
25,0.287984,0.312913,0.215737,0.107467,0.049655,0.016121,0.006754,0.002484,0.000675,0.000182,0.000028
26,0.255426,0.306190,0.232881,0.119208,0.056683,0.017959,0.007767,0.002844,0.000758,0.000244,0.000039
27,0.226731,0.297747,0.248446,0.130468,0.063692,0.019721,0.008788,0.003199,0.000838,0.000319,0.000052
28,0.235497,0.299793,0.244135,0.127272,0.061486,0.019151,0.008459,0.003057,0.000809,0.000293,0.000047
29,0.267523,0.307215,0.227537,0.115465,0.054039,0.017230,0.007372,0.002648,0.000719,0.000219,0.000033
30,0.280594,0.302213,0.225260,0.113858,0.051553,0.016392,0.006965,0.002290,0.000656,0.000194,0.000026
31,0.237653,0.301942,0.242058,0.125782,0.060902,0.019047,0.008386,0.003084,0.000810,0.000288,0.000047
32,0.271827,0.304462,0.227477,0.115398,0.053249,0.016931,0.007234,0.002490,0.000692,0.000210,0.000030
33,0.342429,0.305252,0.196193,0.094860,0.040306,0.013286,0.005352,0.001683,0.000512,0.000113,0.000014
34,0.311852,0.309027,0.207797,0.102238,0.045361,0.014801,0.006098,0.002064,0.000594,0.000147,0.000020
35,0.252107,0.298097,0.239046,0.123502,0.057701,0.018023,0.007862,0.002642,0.000734,0.000250,0.000036
36,0.228602,0.308343,0.241356,0.125439,0.062868,0.019808,0.008747,0.003576,0.000884,0.000317,0.000059
37,0.251187,0.297932,0.239495,0.123823,0.057912,0.018078,0.007893,0.002655,0.000737,0.000252,0.000036
38,0.224355,0.298833,0.248595,0.130619,0.064255,0.019916,0.008886,0.003305,0.000855,0.000327,0.000055
39,0.301710,0.304103,0.215194,0.107090,0.047420,0.015269,0.006368,0.002061,0.000603,0.000161,0.000021
40,0.237021,0.295118,0.246430,0.128870,0.061264,0.018948,0.008387,0.002853,0.000780,0.000288,0.000043
41,0.256996,0.307965,0.231204,0.118045,0.056270,0.017890,0.007717,0.002872,0.000760,0.000241,0.000039
42,0.100188,0.236769,0.309238,0.185956,0.110869,0.030790,0.016154,0.006861,0.001479,0.001367,0.000328
43,0.300186,0.308537,0.213182,0.105761,0.047518,0.015403,0.006410,0.002193,0.000623,0.000163,0.000023
44,0.265192,0.308559,0.227650,0.115557,0.054478,0.017392,0.007449,0.002733,0.000732,0.000224,0.000035
45,0.231173,0.301729,0.244485,0.127588,0.062470,0.019492,0.008629,0.003238,0.000838,0.000307,0.000051
46,0.342429,0.305252,0.196193,0.094860,0.040306,0.013286,0.005352,0.001683,0.000512,0.000113,0.000014
47,0.290703,0.310306,0.216164,0.107743,0.049242,0.015938,0.006675,0.002369,0.000657,0.000178,0.000026
48,0.214985,0.298436,0.251939,0.133204,0.066683,0.020603,0.009268,0.003561,0.000900,0.000359,0.000063
49,0.202538,0.291586,0.260010,0.139365,0.070250,0.021405,0.009778,0.003663,0.000929,0.000404,0.000070